### ISSUE TITLE
Feature Request:  SideBar specific support

### ISSUE THREAD

**Issue by EstherMoellman** [jingyu9575/tabs-to-bookmark-groups#10]
@jingyu9575 , please, if doable, I'll would like to request the following feature: Specific support for TTBG inside SideBar.

Basically I'm requesting the same SideBar' function [SimpleTabGroups](https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/) and [PowerTabs](https://addons.mozilla.org/en-US/firefox/addon/power-tabs/) have.

I must be honest, to have TTBG in the SidBar as part of the bookmarks... for me is enough.
However, it'll very nice if TTBG can be shown at SideBar in its specific place. It's not really necessary, but definitely it may be a plus!

If you agree to do that, IMO this also may open in the future the opportunity to build options, allowing TTBG to manage tabs directly from SideBar. And this has the potential to make TTBG a very powerful tab manager from SideBar.

Thank you in advance!

**Comment by jingyu9575** [comment]
Adding the extension panel to the sidebar is easy. More functions can be built later.

BTW about GitHub: I think both feature requests and bug reports belong to issues, and I'll remove "not an issue" from the title.

**Comment by EstherMoellman** [comment]
> Adding the extension panel to the sidebar is easy.

Please a question, just to be sure: This is something that can be done from our users side? Or is something you may do in the future?

**Comment by jingyu9575** [comment]
The code has been added. GitHub has a feature of "closing a issue with a commit":

![图片](https://user-images.githubusercontent.com/8923139/73832877-49e6f600-4809-11ea-81b3-bc819217b203.png)

This means with the code change 0446861, the issue is now considered fixed.

The new version has not been published to AMO yet. You can try the [CI build](https://ci.appveyor.com/project/jingyu9575/tabs-to-bookmark-groups/build/artifacts).
