### ISSUE TITLE
What is the difference between "Current Window" and the "+" option?

### ISSUE THREAD

**Issue by Snake883** [jingyu9575/tabs-to-bookmark-groups#17]
What is the difference between "Current Window" and the "+" option?
The both seem to do something with "groups".

Thank you.

**Comment by EstherMoellman** [comment]
I'm not the Dev, but I will try to answer:

The "+" option always will create a new group. If you mouse-hover the "+" , you will see a popup saying "Create group". It's worth mentioning that "+" will create a new group, but not necessarily related to your current window/group. With "+" you can create endless groups, regardless your current window/group. For example, you may want to work at Group1, but "+" may create Group2, Group3 etc, regardless Group1.

"Current window" allows you to save in a new group, all new tabs inside a new different window. It's a way to ensure that tabs in different windows always can be saved in a new group. This "Current window" saves current tabs into new group. You can achieve same function, if in a new window (with opened tabs) you want to change to another window/group... and before leaving the current window/tabs, the icon popup will ask you to save everything into a new group.

**Comment by jingyu9575** [comment]
@snakyjake1 
Current Window: Save the current tabs to a new group, and *associate the window with the group*.
"+": Create a new empty group.

The automatic association seems to be problematic for your use case. For example, if I save tab A, B, C to a group, and then close C, eventually the group will only have A and B because C is removed due to the association. 

I think the extension needs a new mode: no association, delete after loading. (Tracked in #15)
