### ISSUE TITLE
Wrong tab order after restoring a group

### ISSUE THREAD

**Issue by jingyu9575** [jingyu9575/tabs-to-bookmark-groups#3]
@EstherMoellman
Please check again with the latest Firefox the v0.0.20200129 [release](https://github.com/jingyu9575/tabs-to-bookmark-groups/releases). Your Firefox can install unsigned extensions, right?

**Comment by EstherMoellman** [comment]
... confirming, yeap, almost perfect, congrats!... tabs seem to be opened in right order.
I'm using the word "almost", just because when the add-on is installed for the first time => if user has opened tabs => and user creates groups => and user wants to move to another group => then correctly, add-on asks a name for the group of current opened tabs => the user chooses a name => a new different group is opened => but the previous group with opened tabs is not created/saved.
I believe this only happens the first time, at add-on installation, and only happens if user has opened tabs at first installation.

**Comment by jingyu9575** [comment]
This is what I get:

![vKOdPsLvCg](https://user-images.githubusercontent.com/8923139/73444005-09463300-4358-11ea-8294-5179126f8c78.gif)

I did not see any issue.

**Comment by EstherMoellman** [comment]
After lot of tests, here are part of my conclusions:

1) On Nightly's fresh install, yeah, your add-on behaves exactly as the image you posted, saving everything.

2) The issue appears only if you don't use a Nightly' fresh install... it appears if you use your normal daily Nightly.

3) At least with my add-ons, I haven't seen any conflicts, because even deleting all my add-ons, if I use my daily Nightly, the issue appears with your add-on. So, I tend to discard "add-on conflicts" as source of the issue.

4) Same goes to "chrome" folder, user.js and prefs.js... I deleted one by one, and they are not the source of the issue, because the issue stills appears even without "chrome" folder, user.js and new brand prefs.js.

5) I still have lot of items to tests, but my wild guess is that the source of the issue has something to do with "bookmarkbackups", or "sessionstore-backups", or "storage" (temporary containers?), or "sessionstore.jsonlz4". From all these suspect candidates, "storage" seems to me the guilty one. But again, I still need to do more tests.

This is only happening at first install.
Perhaps a simple "alert message" at AMO' page will be enough. You can explain users to install the add-on without tabs, first creating groups, and only then starting to create tabs inside created groups. This will easily solve the issue.

**Comment by jingyu9575** [comment]
I'm not sure if *storage* has any effects here if no other extensions are installed. Probably conflicts with existing bookmarks? Have you tried to uninstall extension, backup and reset the bookmarks, and then reinstall?

**Comment by EstherMoellman** [comment]
Finally I found the source of the issue... and the winner is (LOL): Bookmarks!
The good news is that "normal bookmarks" are not conflicting, your add-on works perfect with old bookmarks.
The issue appeared to me with bookmarks saved by [SimpleTabGroups](https://addons.mozilla.org/en-US/firefox/addon/simple-tab-groups/) add-on. This add-on saves tabs instantaneously as bookmarks (at "Other Bookmarks"). Even if SimpleTabGroups is deleted (removed), those bookmarks remain there. And I don't know why, but if user removed STG, and user is using tabs that were bookmarked by STG (at "Other Bookmarks"), and user installs your your add-on... then the issue appears.

**Comment by jingyu9575** [comment]
Well then remove that conflicting bookmark. This extension is using a "marker" bookmark to find the managed bookmark folder. If this marker is duplicated (e.g. STG creates another bookmark with the same URL), this extension will stop working. 

Now this one and #4 are fixed, the only remaining problem is saving on exit.
