### ISSUE TITLE
Pinned tabs are restored as non-pinned

### ISSUE THREAD

**Issue by jingyu9575** [jingyu9575/tabs-to-bookmark-groups#4]
@EstherMoellman
This depends on the design problem "Whether to use `▶` and `📌` for active and pinned tabs", and it must be determined before the public release, because any changes will cause incompatibility.

I think it is easier to use pictures to show our options:

* **Option 1**: Use custom URL to mark the active or pinned tab:

![Option 1](https://user-images.githubusercontent.com/8923139/73385657-d0617c00-42cd-11ea-9686-eaa52f7c6cba.png)

Good: No title changes
Bad: Cannot see or copy URL from bookmark
Bad: Bookmark icon may become the extension icon
Bad: If the extension is uninstalled and reinstalled later, it may not be able to "decrypt" this link

* **Option 2**: Use symbol in title to mark the active or pinned tab:

![Option 2](https://user-images.githubusercontent.com/8923139/73386490-37336500-42cf-11ea-9058-1adfb0bdb4fc.png)

Good: Easy to find which one is active or pinned
Good: Can see or copy URL from bookmark
Good: Can edit the pinned status by adding or removing the symbol
Good: Will use the real website icon
Bad: Title will include the symbol
Bad: If a website already uses the symbol (e.g. a music player using `▶`), it may be confusing

I prefer option 2. What do you think?

**Comment by EstherMoellman** [comment]
Yeap, option two seems pretty good! Totally agree with you.
Titles using the symbol, honestly, it's not a problem at all. Your two symbols are incredible discrete.
The pinned symbol is very nice... perfect symbol.
For audio playing, if I'm not wrong, the symbol is a speaker (green or red), so I doubt a website will use the symbol you chose (triangle to the right). In the worst case, you can change your triangle symbol with another very unused symbol, for example an "electric lightning" ⚡ ... (or change the color of the triangle, instead black, a kind of orange as the pinned symbol has. This color isonomy will be clear for the user, always identifying this two orange symbols as symbols of your add-on).

And OK, I understand that these two symbols will identify pinned and active tabs in a group. But my question is if you need these two symbols, in order to help the add-on script to use these two symbols, for using pinned and active tabs at the TabBar? I mean, are these two symbols capable to make pinned tab work in different groups? How this will work? What is going to happen when the user has a pinned tab in a group, and he changes group? The pinned tab will close? Or will remain visible?

**Comment by jingyu9575** [comment]
> change the color of the triangle

The symbol has to be an existing emoji, and I cannot find a orange triangle in the emoji list. I think these ones are good candidates: ▶️ 🔘 ☑️ ✔️ ✅ 🔶 🔷 🔸 🔹 

This is how they appear on Firefox: ![Image](https://user-images.githubusercontent.com/8923139/73393679-5f759080-42dc-11ea-8e58-198614236f33.png)

Or we can use the single-color theme: ![Image](https://user-images.githubusercontent.com/8923139/73393780-9350b600-42dc-11ea-9497-c6b72888d339.png)

> if you need these two symbols ...  at the TabBar

No I do not need to change anything at the tab bar. Tab can already be pinned and active; bookmarks cannot be pinned or active in Firefox. This is why I need symbols to add these information to bookmarks.

> What is going to happen when the user has a pinned tab in a group, and he changes group?

Depending on the option. Both are available.

**Comment by EstherMoellman** [comment]
... well, for me the option with the two symbols in black... seemS pretty good.
Both symbols you chose are good, and both in black will be more neutral, also giving isonomy to your add-on.
Honestly, I think is perfect what you chose.
