### ISSUE TITLE
Behaviors on active tab with pinned tabs excluded or included

### ISSUE THREAD

**Issue by jingyu9575** [jingyu9575/tabs-to-bookmark-groups#6]
Before official launch, I just have a question about "active" and pinned "tabs":
In the future will be tremendously useful if you incorporate into TabsToBookmarkGroups, another fantastic add-on of yours: [SelectAfterClosingCurrent](https://addons.mozilla.org/en-US/firefox/addon/select-after-closing-current/). This fusion is a must! But if you don't want to do that, don't worry, users can have same functions using both add-ons.

However, if I use both add-ons, and if I uncheck "exclude pinned tabs" at options (TabsToBookmarkGroups), every time I go into a group with pinned tabs, even if the pinned tab is not the active tab, pinned tabs are loaded with the last active tab. Again, this is happening using or not SelectAfterClosingCurrent. The expected behavior in this case should be to load just the last active tab, pinned or unpinned.

Another undesirable behavior happens, when I check "exclude pinned tabs" at TabsToBookmarkGroups, I choose "pinned tab" as last active tab at SelectAfterClosingCurrent, but when I open a different group at TabsToBookmarkGroups, the last unpinned active tab is loaded (when should be loaded only pinned tabs).

In brief, IMO, those are the expected behaviors:
1) If user checked "exclude pinned tabs" at TabsToBookmarkGroups, when a group is opened, if the last active tab is pinned, then the pinned tab should be the only loaded tab.
2) If user checked "exclude pinned tabs", when a group is opened, if the last active tab is unpinned, then the unpinned tab should be the only loaded tab.
3) If user unchecked "exclude pinned tabs", when a group is opened, if the last active tab is pinned, then the pinned tab should be the only loaded tab.
3) If user unchecked "exclude pinned tabs", when a group is opened, even if the last active tab is an unpinned tab, then the pinned tab should be the only loaded tab.

In simple words:
a) If pinned tabs are included in a group, only last active tab should be loaded, pinned or unpinned, not both.
b) If pinned tabs are excluded, only pinned tabs should be loaded... until user installs TabsToBookmarkGroups and changes this behavior.

_Originally posted by @EstherMoellman in https://github.com/jingyu9575/tabs-to-bookmark-groups/issues/5#issuecomment-580827748_

**Comment by jingyu9575** [comment]
a) is a Firefox bug. See ["Pinned tabs cannot be created and discarded"](https://github.com/mozilla/gecko-dev/blob/7cf35c334b8d401a94433cd372416dae194e062b/browser/components/extensions/parent/ext-tabs.js#L762). I've made a workaround.
b) is now fixed.

Please check the new XPI on the [CI service](https://ci.appveyor.com/project/jingyu9575/tabs-to-bookmark-groups/build/artifacts), not GitHub release. It will always be the latest code. You may need to download it first.

Is there any other important bugs?

**Comment by jingyu9575** [comment]
> incorporate into TabsToBookmarkGroups ...  SelectAfterClosingCurrent

@EstherMoellman I'm afraid merging them will make maintenance difficult. For example, when a bug is found, both extension has to be updated. If the new extension breaks, it will be hard to see whether it is the problem of this one or SelectAfterClosingCurrent. 

There aren't any advantages either. It is both my code, and if my developer account is hacked both will be compromised, whether I merge them or not. The code structure is very different (SelectAfterClosingCurrent is one of my early extensions that cannot use new Firefox features), so there won't be many shared code.

I'd say if you need both features, just install both of them.

**Comment by EstherMoellman** [comment]
F-A-N-T-A-S-T-I-C!
WONDERFUL!
BEAUTIFUL!
Congratulations... very very very nice job.

As I said, I haven't seen other important bugs, and I did a lot of tests finding the worst.
I hope you'll upload to AMO. Below I attach you a list of descriptions for AMO' page, hope it'll be useful for you:

- Tab group manager function, analog to session-store, allowing to group, remember, keep and automatically save tabs as bookmarks.

- Fully tab/bookmark edition through Firefox' bookmark editor, allowing to copy, paste, move, rename, save, import/export and backup tabs/bookmarks. Also, pinned and active tabs are identified.

- Efficiency in terms of browser performance (low RAM consumption, CPU etc).

- No conflicts with Firefox’ functions and other add-ons (when compared to similar add-ons).

- Privacy and security improved due to “bookmarking/closing” tabs (instead of “hiding/discarding” tabs). By “bookmarking/closing”, when a tab is closed and Firefox closes, everything will be deleted, avoiding tracking.

- Last active tab always remembered per group. Different behaviors can be achieved by using [SelectAfterClosingCurrent](https://addons.mozilla.org/en-US/firefox/addon/select-after-closing-current/).

- Option to ignore (or not ignore) pinned tabs per group.

- Option to unload tabs until selected/active (saving RAM, CPU etc).

- Less need of other add-ons, reducing conflicts and negative browser performance.

- New features to be included in the future.

PS: Just as a reminder, at AMO' page is important to alert about first opened page on add-on install, asking for "restore previous session".

**Comment by jingyu9575** [comment]
Published to AMO: https://addons.mozilla.org/firefox/addon/tabs-to-bookmark-groups/

**Comment by EstherMoellman** [comment]
@jingyu9575 ,

Firstly: T-H-A-N-K Y-O-U!... from the bottom of my heart, thank you.
Secondly: C-O-N-G-RA-T-S! Be proud of yourself, you did an amazing job.

Double big hug! :)

PS1: I don't know where you live in China, but I worry about you and coronavirus.

PS2: If you live in Hong Kong, I also worry about you and the political situation.

PS3: Have a happy Chinese New year!

**Comment by jingyu9575** [comment]
I'm currently abroad for a study project and I'm fine here. Thank you!
